# coding=utf-8
# *** WARNING: this file was generated by pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_opnsense.config as __config
    config = __config
    import pulumi_opnsense.unbound as __unbound
    unbound = __unbound
else:
    config = _utilities.lazy_import('pulumi_opnsense.config')
    unbound = _utilities.lazy_import('pulumi_opnsense.unbound')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "opnsense",
  "mod": "unbound",
  "fqn": "pulumi_opnsense.unbound",
  "classes": {
   "opnsense:unbound:HostAlias": "HostAlias",
   "opnsense:unbound:HostOverride": "HostOverride"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "opnsense",
  "token": "pulumi:providers:opnsense",
  "fqn": "pulumi_opnsense",
  "class": "Provider"
 }
]
"""
)
