// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/oss4u/pulumi-opnsense-native/sdk/go/opnsense/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The username. Its important but not secret.
func GetFw_api_address(ctx *pulumi.Context) string {
	return config.Get(ctx, "opnsense:fw_api_address")
}

// The password. It is very secret.
func GetFw_api_key(ctx *pulumi.Context) string {
	return config.Get(ctx, "opnsense:fw_api_key")
}

// The (entirely uncryptographic) hash function used to encode the "password".
func GetFw_api_secret(ctx *pulumi.Context) string {
	return config.Get(ctx, "opnsense:fw_api_secret")
}
