// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Immutable;

namespace Oss4u.Opnsense
{
    public static class Config
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "IDE1006", Justification = 
        "Double underscore prefix used to avoid conflicts with variable names.")]
        private sealed class __Value<T>
        {
            private readonly Func<T> _getter;
            private T _value = default!;
            private bool _set;

            public __Value(Func<T> getter)
            {
                _getter = getter;
            }

            public T Get() => _set ? _value : _getter();

            public void Set(T value)
            {
                _value = value;
                _set = true;
            }
        }

        private static readonly global::Pulumi.Config __config = new global::Pulumi.Config("opnsense");

        private static readonly __Value<string?> _fw_api_address = new __Value<string?>(() => __config.Get("fw_api_address"));
        /// <summary>
        /// The username. Its important but not secret.
        /// </summary>
        public static string? Fw_api_address
        {
            get => _fw_api_address.Get();
            set => _fw_api_address.Set(value);
        }

        private static readonly __Value<string?> _fw_api_key = new __Value<string?>(() => __config.Get("fw_api_key"));
        /// <summary>
        /// The password. It is very secret.
        /// </summary>
        public static string? Fw_api_key
        {
            get => _fw_api_key.Get();
            set => _fw_api_key.Set(value);
        }

        private static readonly __Value<string?> _fw_api_secret = new __Value<string?>(() => __config.Get("fw_api_secret"));
        /// <summary>
        /// The (entirely uncryptographic) hash function used to encode the "password".
        /// </summary>
        public static string? Fw_api_secret
        {
            get => _fw_api_secret.Get();
            set => _fw_api_secret.Set(value);
        }

    }
}
