// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("opnsense");

/**
 * The username. Its important but not secret.
 */
export declare const fw_api_address: string | undefined;
Object.defineProperty(exports, "fw_api_address", {
    get() {
        return __config.get("fw_api_address");
    },
    enumerable: true,
});

/**
 * The password. It is very secret.
 */
export declare const fw_api_key: string | undefined;
Object.defineProperty(exports, "fw_api_key", {
    get() {
        return __config.get("fw_api_key");
    },
    enumerable: true,
});

/**
 * The (entirely uncryptographic) hash function used to encode the "password".
 */
export declare const fw_api_secret: string | undefined;
Object.defineProperty(exports, "fw_api_secret", {
    get() {
        return __config.get("fw_api_secret");
    },
    enumerable: true,
});

