// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("opnsense");

/**
 * The address of the fw. (without /api)
 */
export declare const address: string | undefined;
Object.defineProperty(exports, "address", {
    get() {
        return __config.get("address");
    },
    enumerable: true,
});

/**
 * The key to access the api of the fw.
 */
export declare const key: string | undefined;
Object.defineProperty(exports, "key", {
    get() {
        return __config.get("key");
    },
    enumerable: true,
});

export declare const pluginDownloadURL: string | undefined;
Object.defineProperty(exports, "pluginDownloadURL", {
    get() {
        return __config.get("pluginDownloadURL");
    },
    enumerable: true,
});

/**
 * The secret to access the api of the fw.
 */
export declare const secret: string | undefined;
Object.defineProperty(exports, "secret", {
    get() {
        return __config.get("secret");
    },
    enumerable: true,
});

export declare const version: string | undefined;
Object.defineProperty(exports, "version", {
    get() {
        return __config.get("version");
    },
    enumerable: true,
});

