# coding=utf-8
# *** WARNING: this file was generated by pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

fw_api_address: Optional[str]
"""
The username. Its important but not secret.
"""

fw_api_key: Optional[str]
"""
The password. It is very secret.
"""

fw_api_secret: Optional[str]
"""
The (entirely uncryptographic) hash function used to encode the "password".
"""

