# coding=utf-8
# *** WARNING: this file was generated by pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

address: Optional[str]
"""
The address of the fw. (without /api)
"""

key: Optional[str]
"""
The key to access the api of the fw.
"""

pluginDownloadURL: Optional[str]

secret: Optional[str]
"""
The secret to access the api of the fw.
"""

version: Optional[str]

