# coding=utf-8
# *** WARNING: this file was generated by pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('opnsense')


class _ExportableConfig(types.ModuleType):
    @property
    def address(self) -> Optional[str]:
        """
        The address of the fw. (without /api)
        """
        return __config__.get('address')

    @property
    def key(self) -> Optional[str]:
        """
        The key to access the api of the fw.
        """
        return __config__.get('key')

    @property
    def plugin_download_url(self) -> Optional[str]:
        return __config__.get('pluginDownloadURL')

    @property
    def secret(self) -> Optional[str]:
        """
        The secret to access the api of the fw.
        """
        return __config__.get('secret')

    @property
    def version(self) -> Optional[str]:
        return __config__.get('version')

