# coding=utf-8
# *** WARNING: this file was generated by pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('opnsense')


class _ExportableConfig(types.ModuleType):
    @property
    def fw_api_address(self) -> Optional[str]:
        """
        The username. Its important but not secret.
        """
        return __config__.get('fw_api_address')

    @property
    def fw_api_key(self) -> Optional[str]:
        """
        The password. It is very secret.
        """
        return __config__.get('fw_api_key')

    @property
    def fw_api_secret(self) -> Optional[str]:
        """
        The (entirely uncryptographic) hash function used to encode the "password".
        """
        return __config__.get('fw_api_secret')

