// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package unbound

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"internal"
)

type HostAlias struct {
	pulumi.CustomResourceState

	Length pulumi.IntOutput    `pulumi:"length"`
	Result pulumi.StringOutput `pulumi:"result"`
}

// NewHostAlias registers a new resource with the given unique name, arguments, and options.
func NewHostAlias(ctx *pulumi.Context,
	name string, args *HostAliasArgs, opts ...pulumi.ResourceOption) (*HostAlias, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Length == nil {
		return nil, errors.New("invalid value for required argument 'Length'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource HostAlias
	err := ctx.RegisterResource("opnsense:unbound:HostAlias", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetHostAlias gets an existing HostAlias resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetHostAlias(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *HostAliasState, opts ...pulumi.ResourceOption) (*HostAlias, error) {
	var resource HostAlias
	err := ctx.ReadResource("opnsense:unbound:HostAlias", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering HostAlias resources.
type hostAliasState struct {
}

type HostAliasState struct {
}

func (HostAliasState) ElementType() reflect.Type {
	return reflect.TypeOf((*hostAliasState)(nil)).Elem()
}

type hostAliasArgs struct {
	Length int `pulumi:"length"`
}

// The set of arguments for constructing a HostAlias resource.
type HostAliasArgs struct {
	Length pulumi.IntInput
}

func (HostAliasArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*hostAliasArgs)(nil)).Elem()
}

type HostAliasInput interface {
	pulumi.Input

	ToHostAliasOutput() HostAliasOutput
	ToHostAliasOutputWithContext(ctx context.Context) HostAliasOutput
}

func (*HostAlias) ElementType() reflect.Type {
	return reflect.TypeOf((**HostAlias)(nil)).Elem()
}

func (i *HostAlias) ToHostAliasOutput() HostAliasOutput {
	return i.ToHostAliasOutputWithContext(context.Background())
}

func (i *HostAlias) ToHostAliasOutputWithContext(ctx context.Context) HostAliasOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HostAliasOutput)
}

type HostAliasOutput struct{ *pulumi.OutputState }

func (HostAliasOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**HostAlias)(nil)).Elem()
}

func (o HostAliasOutput) ToHostAliasOutput() HostAliasOutput {
	return o
}

func (o HostAliasOutput) ToHostAliasOutputWithContext(ctx context.Context) HostAliasOutput {
	return o
}

func (o HostAliasOutput) Length() pulumi.IntOutput {
	return o.ApplyT(func(v *HostAlias) pulumi.IntOutput { return v.Length }).(pulumi.IntOutput)
}

func (o HostAliasOutput) Result() pulumi.StringOutput {
	return o.ApplyT(func(v *HostAlias) pulumi.StringOutput { return v.Result }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*HostAliasInput)(nil)).Elem(), &HostAlias{})
	pulumi.RegisterOutputType(HostAliasOutput{})
}
