// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { HostAliasArgs } from "./hostAlias";
export type HostAlias = import("./hostAlias").HostAlias;
export const HostAlias: typeof import("./hostAlias").HostAlias = null as any;
utilities.lazyLoad(exports, ["HostAlias"], () => require("./hostAlias"));

export { HostOverrideArgs } from "./hostOverride";
export type HostOverride = import("./hostOverride").HostOverride;
export const HostOverride: typeof import("./hostOverride").HostOverride = null as any;
utilities.lazyLoad(exports, ["HostOverride"], () => require("./hostOverride"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "opnsense:unbound:HostAlias":
                return new HostAlias(name, <any>undefined, { urn })
            case "opnsense:unbound:HostOverride":
                return new HostOverride(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("opnsense", "unbound", _module)
